function zomato = importZomatoData(filename, dataLines)
%IMPORTFILE1 Import data from a text file
%  ZOMATO = IMPORTFILE1(FILENAME) reads data from text file FILENAME for
%  the default selection.  Returns the data as a table.
%
%  ZOMATO = IMPORTFILE1(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  zomato = importfile1("C:\Users\vijay\Desktop\MATLAB\Zomato-Data-Analysis-main\Zomato-Data-Analysis-main\Dataset\zomato.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 03-Sep-2021 08:14:16

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 21);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["RestaurantID", "RestaurantName", "CountryCode", "City", "Address", "Locality", "LocalityVerbose", "Longitude", "Latitude", "Cuisines", "AverageCostForTwo", "Currency", "HasTableBooking", "HasOnlineDelivery", "IsDeliveringNow", "SwitchToOrderMenu", "PriceRange", "AggregateRating", "RatingColor", "RatingText", "Votes"];
opts.VariableTypes = ["double", "string", "double", "categorical", "string", "categorical", "categorical", "double", "double", "string", "double", "categorical", "categorical", "categorical", "categorical", "categorical", "double", "double", "categorical", "categorical", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["RestaurantName", "Address", "Cuisines"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["RestaurantName", "City", "Address", "Locality", "LocalityVerbose", "Cuisines", "Currency", "HasTableBooking", "HasOnlineDelivery", "IsDeliveringNow", "SwitchToOrderMenu", "RatingColor", "RatingText"], "EmptyFieldRule", "auto");

% Import the data
zomato = readtable(filename, opts);

end